[package]
name = "hnsw"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
rand_core = "0.5.0"
rand_pcg = "0.2.0"
rand_distr = "0.2.1"
rustc-hash = "1.0.1"
hamming-heap = "0.2.0"
generic-array = "0.13.2"
typenum = "1.10.0"

[dev-dependencies]
rand = "0.7.0"
criterion = "0.2.11"

[profile.release]
codegen-units = 1
# This is here so we can generate flamegraphs.
debug = true

