[package]
name = "hnsw"
version = "0.6.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Fast approximate nearest neighbors"
keywords = ["hamming", "distance", "nearest", "neighbor", "search"]
categories = ["algorithms", "data-structures", "science"]
repository = "https://github.com/rust-cv/hnsw"
documentation = "https://docs.rs/hnsw/"
license = "MIT"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
serde1 = ["serde", "generic-array/serde", "rand_pcg/serde1", "space/serde", "hashbrown/serde"]

[dependencies]
space = { version = "0.10.2", features = ["candidates-vec"] }
rand_core = "0.5.0"
rand_pcg = "0.2.0"
rustc-hash = { version = "1.1.0", default-features = false }
generic-array = "0.13.2"
typenum = "1.10.0"
hashbrown = "0.7.0"
serde = { version = "1.0", features = ["derive"], optional = true }
libm = "0.2.1"

[dev-dependencies]
space = { version = "0.10.2", features = ["simd"] }
rand_distr = "0.2.1"
hamming-heap = "0.4.1"
rand = "0.7.0"
criterion = "0.2.11"
gnuplot = "0.0.34"
structopt = "0.2.18"
easybench = "0.1.4"
itertools = "0.8.0"
float-ord = "0.2.0"
byteorder = "1.3.2"

[profile.dev]
# The tests take a very long time without optimization.
opt-level = 3

[profile.release]
codegen-units = 1
# This is here so we can generate flamegraphs.
debug = true
